apiVersion: v1
kind: Namespace
metadata:
  name: username
  labels:
    managed-by: k8s-provisioner
    provisioned: "true"

---
#Service Account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: username
  namespace: username
subjects:
  - kind: User
    name: https://keycloak.zerofiltre.tech/auth/realms/zerofiltre-k8s-oidc-authentication#user_id
    apiGroup: rbac.authorization.k8s.io

roleRef:
  kind: ClusterRole
  name: read-write-all-except-resourcequotas
  apiGroup: rbac.authorization.k8s.io

---
# Ressource quotas
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-limits
  namespace: username
spec:
  hard:
    pods: "20"
    requests.cpu: "100m"
    requests.memory: 2Gi
    limits.cpu: "500m"
    limits.memory: 4Gi
